---
- name: restart orchestrator
  command: >-
    nomad job restart
    {{ ('-token=' ~ (hostvars[groups['nomad_server'][0]]['nomad_acl_token'] | default(nomad_token | default('')))) if (nomad_acl_enabled | bool) else '' }}
    e2b-orchestrator
  delegate_to: "{{ groups['nomad_server'][0] }}"
