[postgresql]
pg-1 ansible_host=10.0.1.10 pg_role=primary
pg-2 ansible_host=10.0.1.11 pg_role=replica
pg-3 ansible_host=10.0.1.12 pg_role=replica

[redis]
redis-1 ansible_host=10.0.1.20 redis_role=master
redis-2 ansible_host=10.0.1.21 redis_role=slave
redis-3 ansible_host=10.0.1.22 redis_role=slave

[redis_sentinel]
sentinel-1 ansible_host=10.0.1.20
sentinel-2 ansible_host=10.0.1.21
sentinel-3 ansible_host=10.0.1.22

[nomad_server]
nomad-1 ansible_host=10.0.1.30
nomad-2 ansible_host=10.0.1.31
nomad-3 ansible_host=10.0.1.32

[nomad_client]
compute-1 ansible_host=10.0.1.40
compute-2 ansible_host=10.0.1.41
compute-3 ansible_host=10.0.1.42

[api]
api-1 ansible_host=10.0.1.50
api-2 ansible_host=10.0.1.51
api-3 ansible_host=10.0.1.52

[client_proxy]
proxy-1 ansible_host=10.0.1.60
proxy-2 ansible_host=10.0.1.61

[lb]
lb-1 ansible_host=10.0.1.70

[dashboard_api]
dashboard-api-1 ansible_host=10.0.1.90
dashboard-api-2 ansible_host=10.0.1.91

[dashboard]
dashboard-1 ansible_host=10.0.1.90
dashboard-2 ansible_host=10.0.1.91

[clickhouse:vars]
clickhouse_optional=true

[clickhouse]
ch-1 ansible_host=10.0.1.80

[loki:vars]
loki_optional=true

[loki]
loki-1 ansible_host=10.0.1.81

[e2b:children]
postgresql
redis
nomad_server
nomad_client
api
client_proxy
dashboard_api
dashboard
lb
